name: Deploy to shinyapps.io

on:
  push:
    branches: [main]  # or change this to your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Verify Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.340/quarto-1.3.340-linux-amd64.deb
          sudo dpkg -i quarto-1.3.340-linux-amd64.deb
          export PATH=$PATH:/usr/bin:/usr/local/bin
          quarto --version

      - name: Deploy to shinyapps.io using custom action
        uses: nogunmesa/shinyapps-deploy-github-action@main
        with:
          appName: GrinnellBaseballPCA
          accountName: baseballteam
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
