name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Deploy to shinyapps.io
        uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
        with:
          appDir: .
          appName: GrinnellBaseballPCA
          accountName: ${{ secrets.SHINYAPPS_NAME }}
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
