name: Deploy to shinyapps.io

on:
  push:
    branches: [main]  # or whatever branch you deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Verify Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.340/quarto-1.3.340-linux-amd64.deb
          sudo dpkg -i quarto-1.3.340-linux-amd64.deb
          # Explicitly set the PATH to include Quarto
          export PATH=$PATH:/usr/bin:/usr/local/bin
          # Verify installation
          quarto --version

      - name: Deploy to shinyapps.io
        uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
        with:
          appName: GrinnellBaseballPCA
          accountName: baseballteam
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
          forceUpdate: true  # Ensure the app is overwritten if it already exists
          appId: 14845397 
