            - name: Deploy to shinyapps.io
  # You may pin to the exact commit or the version.
  # uses: BDSI-Utwente/shinyapps-deploy-github-action@f745602f8cf536527835597784813b3fcc520f63
  uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
  with:
    # path to app, relative to repository root. Defaults to the repository root.
    appDir: # optional
    # comma separated list of files to publish, relative to appDir. If not provided, all files in appDir will be published.
    appFiles: # optional
    # path to manifest file, listing files to be deployed relative to appDir.
    appFileManifest: # optional
    # name of the application (typically the last part of the url, e.g. https://<account>.shinyapps.io/<appName>).
    appName: 
    # user-friendly title for the application
    appTitle: # optional
    # level of verbosity of rsconnect::deployApp(). Defaults to "normal", other options are "quiet" or "verbose".
    logLevel: # optional, default is normal
    # account name on shinyapps.io (typically the first part of the url, e.g. https://<account>.shinyapps.io/<appName>).
    accountName: 
    # access token, see https://www.shinyapps.io/admin/#/tokens. Generating a new token/secret pair for this action is recommended, so that you can revoke it without affecting other deployments.
    accountToken: 
    # secret, see https://www.shinyapps.io/admin/#/tokens. Generating a new token/secret pair for this action is recommended, so that you can revoke it without affecting other deployments.
    accountSecret: 
          
