name: Deploy to shinyapps.io

on:
  push:
    branches: [main]  # or whatever branch you deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Disable Quarto
        run: touch .noquarto

      - name: Deploy to shinyapps.io
        uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
        with:
          appName: GrinnellBaseballPCA
          accountName: YOUR_ACCOUNT
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
